homeSuccess:
  customize:
    01_communityTopicList:
      template: [communityTopic, communityTopicList]
      parts:    [communityMember]
      target:   [before]
      is_component: true

    02_communityEventList:
      template: [communityEvent, communityEventList]
      parts:    [communityMember]
      target:   [before]
      is_component: true

    03_searchFormLine:
      template: [communityTopic, searchFormLine]
      parts:    [communityMember]
      target:   [before]
      is_component: false

    configNotificationMail:
      template: [communityTopic, configNotificationMail]
      parts: [communityMember]
      target: [before]
      is_component: true

searchSuccess:
  customize:
    topicSearchLink:
      template: [communityTopic, topicSearchLink]
      parts:    [searchCommunity]
      target:   [after]
      is_component: false
